{% set name = "videogrep" %}
{% set python_min = "3.8" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 180a4bd2ea8ba5566f59acf94edbbcb03514f745b9818594ba9bfd75bb4c4086

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  entry_points:
    - videogrep = videogrep.cli:main

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }}
    - beautifulsoup4
    - imageio
    - moviepy
    # vosk ==0.3.32 is an optional dependency but not currently on conda-forge

test:
  requires:
    - python {{ python_min }}
  commands:
    - videogrep -h
  imports:
    - videogrep

about:
  home: http://antiboredom.github.io/videogrep
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: automatic video supercuts with python

  description: |
    Videogrep is a command line tool that searches through dialog in video
    files (using .srt or .vtt subtitle tracks, or pocketsphinx transcriptions)
    and makes supercuts based on what it finds.
  doc_url: http://antiboredom.github.io/videogrep
  dev_url: https://github.com/antiboredom/videogrep

extra:
  recipe-maintainers:
    - kynan
