{% set name = "videogrep" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 619639b58b767a9cd89245930c14070c522f740e5ee70196d03e761e98981afc

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [win]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - audiogrep
    - beautifulsoup4
    - decorator
    - imageio
    - moviepy
    - numpy
    - pillow
    - pydub
    - tqdm
    - requests

test:
  commands:
    - videogrep -h
  imports:
    - videogrep

about:
  home: http://antiboredom.github.io/videogrep
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: automatic video supercuts with python

  description: |
    Videogrep is a command line tool that searches through dialog in video
    files (using .srt or .vtt subtitle tracks, or pocketsphinx transcriptions)
    and makes supercuts based on what it finds.
  doc_url: http://antiboredom.github.io/videogrep
  dev_url: https://github.com/antiboredom/videogrep

extra:
  recipe-maintainers:
    - kynan
