# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "TwARdBSYJ6qYA4kQ5Sp7YvaGUe9IxN39+5o3B++lbEZicyKq/zhc50ETX0K+vp4DZwU+S7QyZvOXn5DIbVPRWsYYslvPTsq07NHsEZFD35zTMKyQa3DPyAo9NTx4EQPCpCf9ltg+9RAf3V0qqM9LpGhEKzh0AYVCyH1YJU4KYXpJMiCz/01S2aPAsrSUY89vMoM3uQVAOgnEMrKWOY8It0WG8au4H94qrpDxL6bH2+Wz6yElGv/qXHjMf35RPBAuwzEy+zZrBUAPn8zz6Ro1SO0wJs4nB7IUIsoebUPRM5FPFmSFdYx66odOJR2manIU1QfHO9lgStoBPhg/ZjD/VBOwWPi57pYmXi5PLBihYKFceU/quVUQsLL8k3kwKd+CGHGMxMzpaLhQAhCFssBoIALajE17oJsKOEk0NJYNhI1WRcIdPgHsHB8oJDa8jT56GsCT46pUsHPsED0rFB58OQqmZA0hiBkAWw7r3Cx1dJjjZb1W/oclc59cAdGNTAvbr3HkANeE1lxS0kkSA0h7MYLM5zpe2ZOLI+Ah+WRKVveWJjjSh10ZlU60/Z/W9Id4i7DriXn76dIdv1zzEKrURRJj4BZKyTp76o5t+Jpjiz60T8mAt+UQt1qsJ4b7HGiz6pahgtNhIbYTZRLg1mr7CKb94nMuDEAf5WX/hhAMvQs="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml