appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: TwARdBSYJ6qYA4kQ5Sp7YvaGUe9IxN39+5o3B++lbEZicyKq/zhc50ETX0K+vp4DZwU+S7QyZvOXn5DIbVPRWsYYslvPTsq07NHsEZFD35zTMKyQa3DPyAo9NTx4EQPCpCf9ltg+9RAf3V0qqM9LpGhEKzh0AYVCyH1YJU4KYXpJMiCz/01S2aPAsrSUY89vMoM3uQVAOgnEMrKWOY8It0WG8au4H94qrpDxL6bH2+Wz6yElGv/qXHjMf35RPBAuwzEy+zZrBUAPn8zz6Ro1SO0wJs4nB7IUIsoebUPRM5FPFmSFdYx66odOJR2manIU1QfHO9lgStoBPhg/ZjD/VBOwWPi57pYmXi5PLBihYKFceU/quVUQsLL8k3kwKd+CGHGMxMzpaLhQAhCFssBoIALajE17oJsKOEk0NJYNhI1WRcIdPgHsHB8oJDa8jT56GsCT46pUsHPsED0rFB58OQqmZA0hiBkAWw7r3Cx1dJjjZb1W/oclc59cAdGNTAvbr3HkANeE1lxS0kkSA0h7MYLM5zpe2ZOLI+Ah+WRKVveWJjjSh10ZlU60/Z/W9Id4i7DriXn76dIdv1zzEKrURRJj4BZKyTp76o5t+Jpjiz60T8mAt+UQt1qsJ4b7HGiz6pahgtNhIbYTZRLg1mr7CKb94nMuDEAf5WX/hhAMvQs=}
conda_forge_output_validation: true
